import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ModalProvider } from './providers/modal';
import Modal from '../components/modal';

export const metadata: Metadata = {
  title: 'FinLife',
  // description: 'Generated by create next app',
}
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative`}>
        <ModalProvider>
          {children}

          <Modal />
        </ModalProvider>
      </body>
    </html>
  )
}
