import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { MaterialThemeProvider } from '@/providers/material-theme';
import { DatePickerProvider } from '@/providers/date-picker';
import { LoadingProvider } from '@/providers/loading';
import { ModalProvider } from '@/providers/modal';

export const metadata: Metadata = {
  title: 'FinLife',
  // description: 'Generated by create next app',
}
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative`}>
        <MaterialThemeProvider>
          <DatePickerProvider>
            <LoadingProvider>
              <ModalProvider>
                {children}
              </ModalProvider>
            </LoadingProvider>
          </DatePickerProvider>
        </MaterialThemeProvider>
      </body>
    </html>
  )
}
